export const EMAIL_EXISTS = "EMAIL_EXISTS";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const PASSWORD_DO_NOT_MATCH = "PASSWORD_DO_NOT_MATCH";
export const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";